# Generated by Django 5.2.6 on 2025-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(default=18, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('image', models.ImageField(upload_to='profile_pics/', verbose_name='Фото профиля')),
            ],
        ),
    ]
