# Generated by Django 5.2.6 on 2025-09-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics/', verbose_name='Фото профиля'),
        ),
    ]
